services:

  backend:
    image: airflow-support-backend:latest
    container_name: airflow-support-backend
    ports:
      - "8000:8000"

  frontend:
    image: airflow-support-frontend:latest
    container_name: airflow-support-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend