"""Revision-specific source review, authorization and explicit execution orchestration."""
from datetime import datetime, timezone

from backend.app.action_models import ActionRequest, ActionType
from backend.app.action_registry import get_action_policy
from backend.app.actions.airflow import AirflowActionExecutor
from backend.app.airflow_adapter import AirflowAdapter
from backend.app.change_models import (
    SourceRemediation, SourceRemediationState as State, SourceRevision,
    SourceValidation, SourceApproval, SourceAuditEvent,
)
from backend.app.change_review import build_source_code_change_proposal
from backend.app.source_remediation_store import SourceRemediationStore, workflow_lock
from backend.app.source_validation import source_hash
from backend.app.source_updater import DagSourceUpdater, StaleSourceError, read_exact
from backend.app.source_airflow import SourceAirflowVerifier, normalized
from backend.app.verification import VerificationEngine
from backend.app.source_review_validation import resolve_review_source, validate_review_structure
from backend.app.source_execution_policy import POLICY_VERSION, check_record_policy

REVIEWABLE = {State.PROPOSED, State.EDITED, State.VALIDATED, State.VALIDATION_FAILED, State.APPROVED, State.REJECTED}
TERMINAL = {State.SUCCEEDED, State.STALE_SOURCE, State.APPLY_FAILED, State.APPLY_FAILED_ROLLED_BACK,
            State.AIRFLOW_PARSE_FAILED, State.EXECUTION_FAILED, State.VERIFICATION_FAILED}


class SourceRemediationService:
    def __init__(self, store=None, adapter=None):
        self.store = store or SourceRemediationStore()
        self.adapter = adapter
        self.updater = DagSourceUpdater(self.store.path.parent / "source_backups")

    def event(self, record, state, message):
        record.state = state
        record.audit.append(SourceAuditEvent(state=state, message=message, revision=record.revision))
        return self.store.save(record)

    def create(self, before, proposed, patch, provenance, evidence, *, dag_id, investigation=None):
        with workflow_lock:
            path = resolve_review_source(dag_id)
            if source_hash(read_exact(path)) != source_hash(before):
                raise StaleSourceError("Source changed during proposal generation. Investigate again.")
            validate_review_structure(before, proposed, dag_id, patch.target_function)
            change = build_source_code_change_proposal(
                dag_id, f"dags/{dag_id}.py", before, proposed,
                patch.reasoning, generated_by=provenance,
            )
            change.title = patch.summary
            record = SourceRemediation(
                dag_id=dag_id, target_function=patch.target_function, change=change,
                execution_policy_version=POLICY_VERSION, investigation=investigation or {},
                base_source_hash=source_hash(before), original_proposed_source=proposed,
                proposal_hash=source_hash(proposed), evidence=evidence, tests_to_run=patch.tests_to_run,
                revisions=[SourceRevision(revision=1, source=proposed, source_hash=source_hash(proposed), edited_by=provenance)],
            )
            return self.event(record, State.PROPOSED, f"Proposal generated by {provenance}; no DAG source was written.")

    def checked_review(self, proposal_id, revision, digest):
        record = self.store.get(proposal_id)
        if record.state not in REVIEWABLE:
            raise ValueError("This remediation is no longer editable/executable. Start a new investigation.")
        if record.revision != revision or record.proposal_hash != digest:
            raise ValueError("Review revision changed. Reload before continuing.")
        return record

    def edit(self, proposal_id, revision, digest, source, edited_by):
        with workflow_lock:
            record = self.checked_review(proposal_id, revision, digest)
            if source == record.change.source_code.proposed_code:
                return record
            before = record.change.source_code.before_code
            record.change = build_source_code_change_proposal(
                record.dag_id, record.change.source_code.file_path, before, source,
                record.change.description, generated_by=record.change.source_code.generated_by,
            )
            record.revision += 1
            record.proposal_hash = source_hash(source)
            record.validation = None
            record.approval = None
            record.revisions.append(SourceRevision(revision=record.revision, source=source,
                                                   source_hash=record.proposal_hash, edited_by=edited_by))
            # Invalid drafts are saved for editing, but can never be approved/applied.
            try:
                compile(source, "<reviewed-draft>", "exec")
                message = "Reviewed draft saved; syntax passed. Full validation and approval reset."
            except (SyntaxError, ValueError) as exc:
                message = f"Draft saved with invalid syntax: {exc}. Validation and approval reset."
            return self.event(record, State.EDITED, message)

    def validate(self, proposal_id, revision, digest):
        with workflow_lock:
            record = self.checked_review(proposal_id, revision, digest)
            checks, errors = {}, []
            source = record.change.source_code
            checks_to_run = {
                "python_syntax": lambda: compile(source.proposed_code, "<reviewed-source>", "exec"),
                "dag_structure_and_policy": lambda: self._validate_structure(record),
                "target_path": lambda: resolve_review_source(record.dag_id),
                "single_intended_file": lambda: self._check_target(record),
                "source_unchanged": lambda: self._check_base(record),
            }
            for name, check in checks_to_run.items():
                try:
                    check()
                    checks[name] = True
                except (ValueError, SyntaxError, OSError) as exc:
                    checks[name] = False
                    errors.append(f"{name}: {exc}")
            record.validation = SourceValidation(valid=all(checks.values()), revision=revision,
                                                 source_hash=digest, checks=checks, errors=errors)
            record.approval = None
            return self.event(record, State.VALIDATED if record.validation.valid else State.VALIDATION_FAILED,
                              "Review validation completed. Airflow parse validation remains pending until explicit execution.")

    def _check_target(self, record):
        if (record.change.source_code.file_path != f"dags/{record.dag_id}.py"
                or record.change.target != record.dag_id):
            raise ValueError("Only the intended source file is allowed.")

    def _validate_structure(self, record):
        source = record.change.source_code
        validate_review_structure(source.before_code, source.proposed_code, record.dag_id, record.target_function)
        check_record_policy(record)

    def _check_base(self, record):
        if source_hash(read_exact(resolve_review_source(record.dag_id))) != record.base_source_hash:
            raise StaleSourceError("The DAG source changed after proposal creation; investigate again.")

    def approve(self, proposal_id, revision, digest, approved_by, role):
        with workflow_lock:
            record = self.checked_review(proposal_id, revision, digest)
            check_record_policy(record)
            if role not in {"L2", "ADMIN"} or not approved_by.strip():
                raise ValueError("Source remediation requires a named L2 or ADMIN reviewer.")
            if record.state != State.VALIDATED or not record.validation or not record.validation.valid:
                raise ValueError("Validate the exact revision before approval.")
            self._check_base(record)
            record.approval = SourceApproval(revision=revision, source_hash=digest,
                                             approved_by=approved_by.strip(), approver_role=role)
            return self.event(record, State.APPROVED, f"{approved_by} ({role}) approved revision {revision}, SHA-256 {digest}.")

    def reject(self, proposal_id, revision, digest):
        with workflow_lock:
            record = self.checked_review(proposal_id, revision, digest)
            record.approval = None
            return self.event(record, State.REJECTED, "Engineer rejected the reviewed change.")

    def execute(self, proposal_id, revision, digest):
        # Claim once under the process lock; release during polling so GET/audit remains responsive.
        with workflow_lock:
            record = self.checked_review(proposal_id, revision, digest)
            if record.state != State.APPROVED:
                raise ValueError("Approve the exact revision before explicit execution.")
            active = {State.APPLYING, State.APPLIED, State.AIRFLOW_VALIDATING, State.EXECUTING, State.VERIFYING}
            if any(r.dag_id == record.dag_id and r.state in active for r in self.store.all()):
                raise ValueError("Another source remediation is active or interrupted for this DAG. Inspect its audit before proceeding.")
            policy = get_action_policy(ActionType.TRIGGER_DAG)
            if not policy.enabled:
                raise ValueError("DAG trigger policy is disabled.")
            try:
                self.updater.check(record)
            except StaleSourceError as exc:
                return self.event(record, State.STALE_SOURCE, str(exc))
            self.event(record, State.APPLYING, "Explicit execution accepted; checking Airflow and preparing original backup.")
        adapter = self.adapter or AirflowAdapter()
        airflow = SourceAirflowVerifier(adapter)
        try:
            previous = airflow.snapshot(record.dag_id)
            if (normalized(previous["content"]) != normalized(record.change.source_code.before_code)
                    or previous["is_paused"] or previous["is_stale"] or previous["has_import_errors"]):
                raise ValueError("Airflow must be unpaused, healthy and serving the same base source before application.")
            record.backup_path = str(self.updater.backup(record))
            self.event(record, State.APPLYING, "Original bytes backed up; backup path persisted before replacement.")
            self.updater.apply(record)
            record.applied_at = datetime.now(timezone.utc)
            self.event(record, State.APPLIED, "Exact approved bytes atomically applied.")
        except StaleSourceError as exc:
            return self.event(record, State.STALE_SOURCE, str(exc))
        except Exception as exc:
            return self.event(record, State.APPLY_FAILED, f"Source application failed: {exc}")
        self.event(record, State.AIRFLOW_VALIDATING, "Waiting for matching stored Airflow source and a newer parse timestamp.")
        try:
            record.airflow_parse = airflow.wait_for_source(record, previous)
            if source_hash(read_exact(resolve_review_source(record.dag_id))) != record.proposal_hash:
                raise StaleSourceError("Local source changed after application.")
        except Exception as exc:
            self.event(record, State.AIRFLOW_PARSE_FAILED, f"Airflow parse/source verification failed: {exc}")
            try:
                self.updater.rollback(record)
                return self.event(record, State.APPLY_FAILED_ROLLED_BACK,
                                  "Original bytes restored from backup. No corrected run was triggered; Airflow re-parse of rollback is pending.")
            except Exception as rollback_error:
                return self.event(record, State.AIRFLOW_PARSE_FAILED, f"Rollback could not complete: {rollback_error}. Manual recovery required.")
        self.event(record, State.EXECUTING, "Reviewed source recognized. Triggering corrected DAG with empty configuration.")
        try:
            result = AirflowActionExecutor(adapter).execute(ActionRequest(
                action_type=ActionType.TRIGGER_DAG, dag_id=record.dag_id,
                parameters={"conf": {}}, reason=f"Approved source remediation {record.proposal_id}, revision {record.revision}",
            ))
            record.dag_run_id = result.get("dag_run_id")
            if not record.dag_run_id:
                raise ValueError("Airflow did not return a run ID. Check Airflow before any manual retry.")
        except Exception as exc:
            return self.event(record, State.EXECUTION_FAILED, f"Trigger failed or outcome uncertain: {exc}. No automatic retry or rollback.")
        self.event(record, State.VERIFYING, f"Verifying corrected DAG run {record.dag_run_id}.")
        try:
            record.verification = VerificationEngine(adapter).verify_dag_run(record.dag_id, record.dag_run_id)
            if record.verification.get("status") != "verified":
                return self.event(record, State.VERIFICATION_FAILED, "Corrected run did not verify. No automatic patch, retry or rollback.")
            record.verification.update(airflow.verify_run(record))
            if source_hash(read_exact(resolve_review_source(record.dag_id))) != record.proposal_hash:
                raise ValueError("Local reviewed source changed during execution.")
            return self.event(record, State.SUCCEEDED, "Reviewed source, Airflow version, task and DAG success verified.")
        except Exception as exc:
            return self.event(record, State.VERIFICATION_FAILED, f"Verification failed: {exc}. No automatic retry or rollback.")
